version: "{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_API_KEY:
    secure: 3LS4eL/i+vH1q1TL79/y6nYK1FnhByhjH96YpV67mUgjjfZBj4SBMzkz0cfGpqSz
build_script:
- ps: .\build.ps1 --currentBranch=$env:APPVEYOR_REPO_BRANCH --nugetApiKey=$env:NUGET_API_KEY --coverallsToken=$env:COVERALLS_TOKEN
test: off #tests handled by cake script
deploy: off #deploy handled by cake script